service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  index:
    handler: main.index
    events:
      - httpApi:
          path: /
          method: get
  v1_form:
    handler: handlers/v1.v1_form
    events:
      - httpApi:
          path: /v1
          method: get
  v2_form:
    handler: handlers/v2.v2_form
    events:
      - httpApi:
          path: /v2
          method: get
  v3_form:
    handler: handlers/v3.v3_form
    events:
      - httpApi:
          path: /v3
          method: get
  v1_tts:
    handler: handlers/v1.v1_tts
    events:
      - httpApi:
          path: /v1/tts
          method: post
  v2_tts:
    handler: handlers/v2.v2_tts
    events:
      - httpApi:
          path: /v2/tts
          method: post
  v3_tts:
    handler: handlers/v3.v3_tts
    events:
      - httpApi:
          path: /v3/tts
          method: post