service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1_tts:
    handler: v1.v1_tts
    events:
      - httpApi:
          path: /v1/tts
          method: post
  v2_tts:
    handler: v2.v2_tts
    events:
      - httpApi:
          path: /v2/tts
          method: post
  v3_tts:
    handler: v3.v3_tts
    events:
      - httpApi:
          path: /v3/tts
          method: post
  html_route:
    handler: handler.html_route
    events:
      - httpApi:
          path: /home
          method: get