service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: "arn:aws:dynamodb:*:*:table/TTS_References"
        - Effect: Allow
          Action: dynamodb:Scan
          Resource: "arn:aws:dynamodb:*:*:table/TTS_References"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  rota-v1_tts:
    handler: src/rotaV1.tts
    events:
      - http:
          path: /v1/tts
          method: post
          cors: true       
  rota-v2_tts:
    handler: src/rotaV2.create
    events:
      - http:
          path: /v2/tts
          method: post
          cors: true
  rota-v3_tts:
    handler: src/rota.list
    events:
      - http:
          path: /v3/tts
          method: post
          cors: true

resources:
  Resources:
    ttsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TTS_References
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ttsIamRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "ttsDynamoDbAccess"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb: Query"
                  Resource: !GetAtt [ttsDynamoDbTable, Arn] 