service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  v1_form:
    handler: handler.v1_form
    events:
      - httpApi:
          path: /v1
          method: get
  v1_tts:
    handler: handler.v1_tts
    events:
      - httpApi:
          path: /v1/tts
          method: post