service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  # health:
  #   handler: handler.health
  #   events:
  #     - http:
  #         path: /
  #         method: get
  v1_form:
    handler: handler.v1_form
    events:
      - http:
          path: /v1
          method: get
  v1_tts:
    handler: handler.v1_tts
    events:
      - http:
          path: /v1/tts
          method: post
          cors: true

plugins:
  - serverless-python-requirements
